Sprint 1
veniaminryadnov/yandex.messager pull request #1
Opened 2021-11-22 09:46 UTC by veniaminryadnov

2021-11-22 22:00 UTC, avdoshenkov requested changes
Хорошая работа! Особенно порадовало использование шаблонизатора на хорошем уровне, применение форм и наличие лейблов у инпутов

Отметил несколько моментов, которые можно поправить. И ещё несколько советов в целом:
1. Для веба лучше использовать не ttf-расширение, а woff2, woff. Это более современные форматы, поподробнее можно почитать [здесь](https://doka.guide/css/font-face/#kak-pishetsya)
2. Файл app.sass лучше разбить на логические составляющие, т.е. отдельный файл для страницы авторизации, отдельный для профиля и т.д. Так будет удобнее в дальнейшем находить нужные для правок места, а не искать нужную строку по большому документу. все эти части можно хранить рядом с общим файлом и импортировать их в него. Ещё один вариант — хранить стили вместе с файлом шаблона. Тогда в дальнейшем опять же будет удобно редактировать код, поскольку всё, что касается конкретного смыслового блока находится рядом и не придётся терять время на навигацию между папками

2021-11-23 16:21 UTC, veniaminryadnov commented on src/pages/change-password.pug
> +        div.profile__backlink-btn.grid.grid-column.grid-middle
Но внутри div - это обертка для иконки, а идея чтобы весь родительский блок был кликабельный.

2021-11-24 10:20 UTC, avdoshenkov commented on src/pages/change-password.pug
> +        div.profile__backlink-btn.grid.grid-column.grid-middle
Да, я понимаю. В идеале тогда вложенные дивы менять на спаны.. Но ладно, пусть так остаётся

2021-11-24 10:24 UTC, avdoshenkov approved these changes
Класс! Можно смело двигаться дальше

2021-12-13 19:20 UTC, closed without merging